manifest = "e08b3ff1cc931eeab85c2c72ee9beb47ef29f0c2ac456b7a4a057bf605039e9a"

[[dependency]]
package = "github.com/buckaroo-pm/google-googletest"
target = "//:googletest"

[lock."github.com/buckaroo-pm/google-googletest"]
versions = [ "branch=master" ]
revision = "cb8d2c1a2fcd344953e6c129a1a699a2c230551d"
